# Generated by Django 5.2.14 on 2026-05-30 11:44

import common.storage_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0023_sitesettings_whatsapp_cloud_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=common.storage_paths.site_logo_upload_to),
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider')], max_length=20, verbose_name='Tür')),
                ('title', models.CharField(max_length=120, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('record_date', models.DateField(verbose_name='Tarih')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
            ],
            options={
                'verbose_name': 'Gelir/gider kaydı',
                'verbose_name_plural': 'Gelir/gider kayıtları',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
