"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import socket
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from common.panel_env import detect_panel_fqdn, detect_panel_origin, is_http_only_panel_host

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_env_file = BASE_DIR / '.env'
if _env_file.exists():
    try:
        from dotenv import load_dotenv
        load_dotenv(_env_file)
    except ImportError:
        pass


def _lan_ipv4():
    """Outbound interface IP (typical Wi‑Fi address on the local network)."""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(('8.8.8.8', 80))
            return sock.getsockname()[0]
    except OSError:
        return None


def _csrf_origins_for_port(port=8000):
    origins = [
        f'http://localhost:{port}',
        f'http://127.0.0.1:{port}',
    ]
    lan = _lan_ipv4()
    if lan:
        origins.append(f'http://{lan}:{port}')
    return origins


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*t7emu@y2jvbpi(gvcrbvtc*#6(cx)om5=xpzzdd*8y*n&6-ta'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1').lower() in ('1', 'true', 'yes')

# Geliştirme: aynı Wi‑Fi’deki telefon/tablet/PC’ler LAN IP ile bağlanabilsin
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
_env_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _env_hosts:
    ALLOWED_HOSTS.extend(h.strip() for h in _env_hosts.split(',') if h.strip())
_panel_fqdn = detect_panel_fqdn()
if _panel_fqdn and _panel_fqdn not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_panel_fqdn)
_lan_ip = _lan_ipv4()
if _lan_ip and _lan_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_lan_ip)
if DEBUG:
    ALLOWED_HOSTS.append('*')

# Dokploy test domainleri (sslip.io) — üretimde kapalı; geliştirmede açılabilir
_sslip_default = '0' if os.environ.get('DATA_DIR', '').strip() else '1'
if os.environ.get('DJANGO_ALLOW_SSLIP_HOSTS', _sslip_default).lower() in ('1', 'true', 'yes'):
    for _wild in ('.sslip.io', '.traefik.me'):
        if _wild not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_wild)

_env_secret = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if _env_secret:
    SECRET_KEY = _env_secret
elif 'test' not in sys.argv and (not DEBUG or os.environ.get('DATA_DIR', '').strip()):
    raise ImproperlyConfigured(
        'Üretim ortamında DJANGO_SECRET_KEY ortam değişkeni zorunludur.'
    )
elif 'runserver' in sys.argv:
    import warnings

    warnings.warn(
        'Geliştirme SECRET_KEY kullanılıyor. Üretimde DJANGO_SECRET_KEY ayarlayın.',
        stacklevel=1,
    )

_env_csrf = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').strip()
if _env_csrf:
    CSRF_TRUSTED_ORIGINS = [h.strip() for h in _env_csrf.split(',') if h.strip()]
else:
    CSRF_TRUSTED_ORIGINS = _csrf_origins_for_port(8000)
_panel_origin = detect_panel_origin()
if _panel_origin and _panel_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_panel_origin)

WHATSAPP_BRIDGE_URL = os.environ.get('WHATSAPP_BRIDGE_URL', 'http://127.0.0.1:3939').strip()
# Yerel Node köprüsünü Django sürecinden başlatma (Docker/production: 0)
_can_spawn_env = os.environ.get('DJANGO_WHATSAPP_BRIDGE_CAN_SPAWN', '').strip()
if _can_spawn_env:
    WHATSAPP_BRIDGE_CAN_SPAWN = _can_spawn_env.lower() in ('1', 'true', 'yes')
else:
    WHATSAPP_BRIDGE_CAN_SPAWN = not bool(os.environ.get('DATA_DIR', '').strip())
_auto_start_env = os.environ.get('DJANGO_WHATSAPP_BRIDGE_AUTO_START', '').strip()
if _auto_start_env:
    WHATSAPP_BRIDGE_AUTO_START = _auto_start_env.lower() in ('1', 'true', 'yes')
else:
    # Yerelde (spawn açık) runserver/daphne ile Node köprüsünü otomatik aç
    WHATSAPP_BRIDGE_AUTO_START = WHATSAPP_BRIDGE_CAN_SPAWN
WHATSAPP_BRIDGE_AUTO_START_RETRIES = int(os.environ.get('DJANGO_WHATSAPP_BRIDGE_AUTO_START_RETRIES', '15'))
WHATSAPP_BRIDGE_AUTO_START_DELAY = float(os.environ.get('DJANGO_WHATSAPP_BRIDGE_AUTO_START_DELAY', '2'))
WHATSAPP_BRIDGE_RUN_AS_ADMIN = os.environ.get(
    'DJANGO_WHATSAPP_BRIDGE_RUN_AS_ADMIN', '0',
).lower() in ('1', 'true', 'yes')
# Yerel köprü: eksik npm bağımlılıklarını ve (Linux root ise) Node.js'i Django kurar
WHATSAPP_BRIDGE_AUTO_NPM_INSTALL = os.environ.get(
    'DJANGO_WHATSAPP_BRIDGE_AUTO_NPM_INSTALL', '1',
).lower() in ('1', 'true', 'yes')
WHATSAPP_BRIDGE_AUTO_INSTALL_NODE = os.environ.get(
    'DJANGO_WHATSAPP_BRIDGE_AUTO_INSTALL_NODE', '1',
).lower() in ('1', 'true', 'yes')
# İsteğe bağlı: node.exe tam yolu (boşsa Program Files\nodejs aranır; Cursor IDE node'u atlanır)
WHATSAPP_BRIDGE_NODE = os.environ.get('WHATSAPP_BRIDGE_NODE', '').strip()

from common.bridge_token import read_bridge_token  # noqa: E402

WHATSAPP_BRIDGE_TOKEN = read_bridge_token()

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'kobiops-default',
    }
}


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    
    # Local apps
    'users',
    'customers',
    'services',
    'core_settings',
    'analytics',
    'agency',
    'tools',
    'sales_leads',
    'common',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'common.middleware.DokploySslipCsrfMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'common.middleware.LoginRequiredMiddleware',
    'common.middleware.PermissionMiddleware',
    'common.middleware_module_gate.ModuleInstallMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core_settings.context_processors.whatsapp_context',
                'core_settings.context_processors.site_settings',
                'users.context_processors.user_profile_card',
                'users.context_access.user_access',
                'common.context_processors.gy_branding',
                'common.context_processors.module_install_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_db_path = os.environ.get('DJANGO_DB_PATH', '').strip()
if _db_path:
    DATABASES['default']['NAME'] = Path(_db_path)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
_media_root = os.environ.get('DJANGO_MEDIA_ROOT', '').strip()
if _media_root:
    MEDIA_ROOT = Path(_media_root)

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'landing'

_use_secure_ssl = os.environ.get('DJANGO_SECURE_SSL', '').lower() in ('1', 'true', 'yes')
# sslip.io / traefik.me: HTTPS yok; SECURE_SSL=1 → http→https redirect → Traefik 404
if os.environ.get('DJANGO_ALLOW_SSLIP_HOSTS', _sslip_default).lower() in ('1', 'true', 'yes'):
    if '.sslip.io' in ALLOWED_HOSTS or '.traefik.me' in ALLOWED_HOSTS:
        _use_secure_ssl = False
    elif _panel_fqdn and is_http_only_panel_host(_panel_fqdn):
        _use_secure_ssl = False
    elif _panel_origin.startswith('http://'):
        _use_secure_ssl = False

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    if os.environ.get('DATA_DIR', '').strip():
        USE_X_FORWARDED_HOST = True
    if _use_secure_ssl:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        USE_X_FORWARDED_HOST = True
        SECURE_SSL_REDIRECT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Büyük video/belge yüklemeleri (medya paneli)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DJANGO_UPLOAD_MAX_MEMORY', 52 * 1024 * 1024))
DATA_UPLOAD_MAX_NUMBER_FILES = int(os.environ.get('DJANGO_UPLOAD_MAX_FILES', 20))

# Sunucuda medya sıkıştırma (türüne göre)
MEDIA_COMPRESS_ENABLED = os.environ.get('MEDIA_COMPRESS_ENABLED', '1').lower() in ('1', 'true', 'yes')
MEDIA_IMAGE_MAX_SIDE = int(os.environ.get('MEDIA_IMAGE_MAX_SIDE', '1920'))
MEDIA_IMAGE_MAX_QUALITY = int(os.environ.get('MEDIA_IMAGE_MAX_QUALITY', '85'))
MEDIA_IMAGE_FORMAT = os.environ.get('MEDIA_IMAGE_FORMAT', 'JPEG').upper()
MEDIA_FFMPEG_PATH = os.environ.get('MEDIA_FFMPEG_PATH', 'ffmpeg')
MEDIA_FFMPEG_TIMEOUT = int(os.environ.get('MEDIA_FFMPEG_TIMEOUT', '300'))

# Panel içi uygulama güncellemesi (GitHub kontrol + git pull veya deploy webhook)
KOBIOPS_UPDATE_REPO = os.environ.get('KOBIOPS_UPDATE_REPO', 'imyigitcengiz/kobi-ops').strip()
KOBIOPS_UPDATE_BRANCH = os.environ.get('KOBIOPS_UPDATE_BRANCH', 'main').strip()
KOBIOPS_UPDATE_CHECK_INTERVAL = int(os.environ.get('KOBIOPS_UPDATE_CHECK_INTERVAL', '1800'))
KOBIOPS_DEPLOY_WEBHOOK_URL = os.environ.get('KOBIOPS_DEPLOY_WEBHOOK_URL', '').strip()
KOBIOPS_GITHUB_TOKEN = os.environ.get('KOBIOPS_GITHUB_TOKEN', '').strip()
KOBIOPS_BUILD_COMMIT = os.environ.get('KOBIOPS_BUILD_COMMIT', '').strip()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'asyncio': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'PIL': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
