# Generated by Django 5.2.14 on 2026-05-22 11:12

import customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_products'),
        ('services', '0014_servicerecord_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('customer', 'Müşteri dosyası'), ('service', 'Servis dosyası'), ('contract', 'Sözleşme / belge')], default='customer', max_length=20, verbose_name='Kategori')),
                ('file', models.FileField(upload_to=customers.models.customer_media_upload_path, verbose_name='Dosya')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Başlık')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='customers.customer', verbose_name='Müşteri')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='services.servicerecord', verbose_name='Servis')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_media', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Müşteri medyası',
                'verbose_name_plural': 'Müşteri medyaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
