# Generated by Django 5.2.14 on 2026-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermedia',
            name='compress_method',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Sıkıştırma'),
        ),
        migrations.AddField(
            model_name='customermedia',
            name='file_size_original',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal boyut (bayt)'),
        ),
        migrations.AddField(
            model_name='customermedia',
            name='file_size_stored',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Saklanan boyut (bayt)'),
        ),
    ]
